port: 18081
replicaCount: 1
image:
  repository: "striveonger/own-app-api"
  tag: "1.0.0"
  pullPolicy: "IfNotPresent"

probe:
  enabled: true

resources:
  cpu: "2"
  memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

log:
  path: "/var/log/own/app"

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "dev"
  - name: SF_API_KEY
    value: "sk-xyz"