app:
  port: 18081
  replicaCount: 1
  image:
    repository: "striveonger/own-app-api"
    tag: "1.0.0"
    pullPolicy: "IfNotPresent"
  probe:
    enabled: true
  resources:
    cpu: "2"
    memory: "256Mi"
  
  autoscaling:
    minReplicas: 1
    maxReplicas: 10
  log:
    path: "/var/log/own/app"
  config:
    applicationYaml:
      logging:
        level:
          root: info
      own:
        app:
          storage:
            memory:
              max-rows: 10