logging:
  level:
    root: info
  file:
    path: logs



spring:
  application:
    name: own-app
  ai:
    openai:
      base-url: "https://api.siliconflow.cn"
      api-key: "${SF_API_KEY}"
      chat:
        completions-path: "/v1/chat/completions"
        options:
          temperature: 0.85
          # model: "Qwen/Qwen3-8B"
          model: "Qwen/Qwen3-32B"
          # model: "Qwen/Qwen3-235B-A22B"

own:
  example-app:
    storage:
      memory:
        max-rows: 10
