{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "own-app-ui.name" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "own-app-ui.labels" .  | indent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`{{ .Values.ingress.path }}`)
      kind: Rule
      services:
        - name: "{{ include "own-app-ui.name" . }}-service"
          port: 80
{{- end -}}