apiVersion: "v1"
kind: "Service"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: {{ include "own-app-ui.name" . }}-service
  labels:
{{ include "own-app-ui.labels" .  | indent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - protocol: "TCP"
      name: http
      port: 80
      targetPort: {{ .Values.port }}
  sessionAffinity: "None"
  selector:
{{ include "own-app-ui.selectorLabels" .  | indent 4 }}
