---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ include "own-app-api.name" . }}-deployment"
  labels:
{{ include "own-app-api.labels" .  | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "own-app-api.selectorLabels" .  | indent 6 }}
  template:
    metadata:
      namespace: "{{ .Release.Namespace }}"
      name: "{{ include "own-app-api.name" . }}"
      labels:
{{ include "own-app-api.labels" .  | indent 8 }}
    spec:
      restartPolicy: "Always"
      containers:
        - name: "{{ include "own-app-api.name" . }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{.Values.image.pullPolicy }}"
          resources:
            limits:
              cpu: "{{ .Values.resources.cpu }}"
              memory: "{{ .Values.resources.memory }}"
            requests:
              cpu: "{{ .Values.resources.cpu }}"
              memory: "{{ .Values.resources.memory }}"
          ports:
            - containerPort: {{ .Values.port }}
              protocol: "TCP"
          livenessProbe:
{{ include "common.probe.liveness" . | indent 12 }}
          readinessProbe:
{{ include "common.probe.readiness" . | indent 12}}
          env:
{{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
{{ include "common.volumeMounts" . | indent 12}}
      volumes:
{{ include "common.volumes" . | indent 8}}