apiVersion: "v1"
kind: "Service"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: {{ include "own-app.name" . }}-service
  labels:
{{ include "own-app.labels" .  | indent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: {{ .Values.app.port }}
  sessionAffinity: "ClientIP"
  selector:
{{ include "own-app.selectorLabels" .  | indent 4 }}
